# Указываем, что используем railpacks
[build]
builder = "railpacks"

# Указываем, что это Cron-задача
[cron]
# Запускать каждые 5 минут
schedule = "*/5 * * * *"
# Команда, которая будет выполняться
command = "python app.py"